### ISSUE TITLE
Implementation checklist

### ISSUE THREAD

**Issue by oleganza** [interstellar/zkvm#5]
This is a tracking issue for ZkVM implementation.

- [x] vm: Predicate tree: disjunction and program commitment: #4
- [x] vm: aggregated signature protocol: #4, #8
- [x] vm: batched verification of point operations: #16
- [x] vm: VM state with basic input+signtx+cloak+output flow: #4
- [x] vm: encoding inputs/outputs: #4
- [x] vm: merkle tree for txid: #4
- [ ] api: prover: low-level API: convert a stream of `Instruction`s into a program bytecode, tx sig and r1cs proof. PR: TBD
- [ ] api: prover: high-level input-output txbuilder on top of the low-level API.
- [ ] api: prover: issuance txbuilder: add optional nonce if no inputs are present
- [ ] api: prover: retirement (add an API for destroying a value)
- [ ] api: prover: make txid-inclusion proof for chosen outputs
- [ ] vm: `left`/`right` instructions
- [ ] vm: `delegate`/`call` instructions
- [ ] vm: `contract` instruction
- [x] vm: `log` instruction #20
- [ ] api: txbuilder: add data-only (`log`) entry API
- [ ] api: payment channel protocol
- [ ] api: vault protocol
- [ ] vm: `mintime`/`maxtime` instructions
- [ ] vm: `qty`/`flavor` instructions
- [ ] vm: `var`/`const` instructions
- [ ] vm: `neg`/`add`/`mul` instructions
- [ ] vm: `eq`/`and`/`or`/`verify` instructions
- [ ] vm: `alloc` instruction
- [ ] vm: `import`/`export` instructions
- [ ] vm: `blind`/`reblind`/`unblind` instructions

**Comment by oleganza** [comment]
Moving to https://github.com/interstellar/slingshot/issues/59
